import { redirect } from "next/navigation";
import Container from "@/components/Container";
import PageHeader from "@/components/app/PageHeader";
import { getSession } from "@/lib/auth";
import {
  getRecentMindCheckLogs,
  getTodayMentalCoachOutput,
  getTodayMindCheck,
  getTodayPersonalSession,
  hasAcknowledgedMentalDisclaimer,
  persistMentalCoachOutput,
  persistPersonalSession,
} from "@/lib/data/mind";
import SessionRunner from "@/components/mind/SessionRunner";
import CoachReflection from "@/components/mind/CoachReflection";
import { buildCoachContext, computeMentalSignal } from "@/lib/mind/coach-context";
import { generatePersonalSession } from "@/lib/mind/session-generator-claude";
import { buildFallbackSession } from "@/lib/mind/session-fallback";
import { generateMentalCoachOutput } from "@/lib/mind/coach-claude";
import { buildFallbackCoachOutput } from "@/lib/mind/coach-fallback";

export const metadata = {
  title: "I dag · Mind · MakeIt",
};

/**
 * `/mind/today` — daily destination.
 *
 * Shows today's personal mental session (generated by Claude in MH-4,
 * pre-warmed by the cron in MH-7). Generates inline on first visit
 * each day for members who arrive before the cron runs.
 *
 * MH-7 layers a personal Claude-written reflection above the session.
 */
export default async function MindTodayPage() {
  const member = await getSession();
  if (!member) redirect("/login");
  if (!(await hasAcknowledgedMentalDisclaimer(member.id))) {
    redirect("/mind/onboarding");
  }

  const today = new Date().toISOString().slice(0, 10);

  const coachOutput = await getTodayMentalCoachOutput(member.id);
  let session = await getTodayPersonalSession(member.id);

  // First visit of the day — generate inline. The cron pre-warms
  // this in production; this branch handles the demo + edge cases.
  if (!session) {
    const [todayMc, logs] = await Promise.all([
      getTodayMindCheck(member.id),
      getRecentMindCheckLogs(member.id, 7),
    ]);

    const signal = computeMentalSignal(logs);
    const ctx = buildCoachContext({
      member: { handle: member.handle, tier: member.tier },
      mindToday: todayMc
        ? {
            energy: todayMc.energy,
            stress: todayMc.stress,
            focus: todayMc.focus,
            note: todayMc.note,
          }
        : null,
      signal,
      hrv: {
        week_mean_rmssd_ms: null,
        prior_week_mean_rmssd_ms: null,
        week_reading_count: 0,
      },
      training: {
        sessions_completed_7d: 0,
        sessions_planned_7d: 0,
        last_session_rpe: null,
        last_session_was: null,
      },
      forDate: today,
    });

    const generated = await generatePersonalSession(ctx);
    const script = generated?.script ?? buildFallbackSession(ctx);

    const persisted = await persistPersonalSession({
      memberId: member.id,
      forDate: today,
      script,
      promptSeed: null,
      generatedBy: generated ? "claude" : "imported",
    });

    session = persisted
      ? {
          id: persisted.id,
          slug: `personal-${member.id}-${today}`,
          title: script.title,
          subtitle: script.subtitle,
          body_md: script.body_md,
          visual_pattern: script.visual_pattern,
          duration_seconds: script.duration_seconds,
          category: script.category,
        }
      : {
          id: "ephemeral",
          slug: `ephemeral-${today}`,
          title: script.title,
          subtitle: script.subtitle,
          body_md: script.body_md,
          visual_pattern: script.visual_pattern,
          duration_seconds: script.duration_seconds,
          category: script.category,
        };
  }

  // If no coach output yet today, generate inline (cron pre-warms in
  // production but the demo + edge cases need the fallback path).
  let coachBody: string | null = coachOutput?.body_md ?? null;
  if (!coachBody) {
    const [todayMc, logs] = await Promise.all([
      getTodayMindCheck(member.id),
      getRecentMindCheckLogs(member.id, 7),
    ]);
    const signal = computeMentalSignal(logs);
    const ctx = buildCoachContext({
      member: { handle: member.handle, tier: member.tier },
      mindToday: todayMc
        ? {
            energy: todayMc.energy,
            stress: todayMc.stress,
            focus: todayMc.focus,
            note: todayMc.note,
          }
        : null,
      signal,
      hrv: {
        week_mean_rmssd_ms: null,
        prior_week_mean_rmssd_ms: null,
        week_reading_count: 0,
      },
      training: {
        sessions_completed_7d: 0,
        sessions_planned_7d: 0,
        last_session_rpe: null,
        last_session_was: null,
      },
      forDate: today,
    });
    const generated = await generateMentalCoachOutput(ctx);
    coachBody = generated?.bodyMd ?? buildFallbackCoachOutput(ctx);
    await persistMentalCoachOutput({
      memberId: member.id,
      forDate: today,
      bodyMd: coachBody,
      promptSeed: { source: generated ? "claude" : "fallback" },
    });
  }

  return (
    <>
      <PageHeader
        eyebrow="Mind · I dag"
        title="Dagens refleksion."
        subtitle="Personlig refleksion + session — bygget til din mind-check, HRV og uge."
      />
      <Container size="narrow" className="py-10 md:py-14 space-y-12">
        <CoachReflection bodyMd={coachBody} />

        <SessionRunner
          sessionId={session.id}
          title={session.title}
          subtitle={session.subtitle}
          bodyMd={session.body_md}
          visualPattern={session.visual_pattern}
          durationSeconds={session.duration_seconds}
          context="library"
        />
      </Container>
    </>
  );
}
